### ISSUE TITLE
Replace all remaining (breaking) references to Packet

### ISSUE THREAD

**Issue by alice-sowerby** [packet-labs/terraform-packet-distributed-minio#16]
All non-breaking changes have been made. Remaining breaking changes still need to be done. 

1. Repo name `terraform-packet-distributed-minio` can be changed to `terraform-distributed-minio`
2. `git clone https://github.com/packet-labs/terraform-packet-distributed-minio.git`
3. About section 
>About
**packet-distributed-minio** is a Terraform template that will deploy Minio distributed on Equinix Metal **baremetal**.

**Comment by deitch** [comment]
This is basically done, except that we need to actually rename the repo. I think you have the rights to it @DailyAlice ? I am not an admin on this repo. It needs to become `terraform-distributed-minio`.
