### ISSUE TITLE
Apply Packet Experimental repository standards

### ISSUE THREAD

**Issue by displague** [packet-labs/terraform-packet-distributed-minio#2]
Thanks, @enkelprifti98 and @dsieczko for your contributions thus far in starting this awesome project!

Now that this is in the Packet Labs org, we want to ensure that the project meets our (new!) standards for such projects.

The _Experimental Tier Minimum Requirements_ are as follows:

* [x] The Experimental badge
* [x] The Experimental Statement in the README.md
* [x] LICENSE
* [x] README.md
* [x] OWNERS.md
* [x] Developer Certificate of Origin https://github.com/apps/dco
* [x] At least one maintainer
* [x] CI/CD

We may update these standards along the way as @DailyAlice, @rainleander, and others iron out the process.

**Comment by rainleander** [comment]
Done!
