### ISSUE TITLE
Apply Packet Maintained repository standards

### ISSUE THREAD

**Issue by displague** [packet-labs/terraform-packet-distributed-minio#3]
Blocked by #2 

Once this repository has cleared the hurdles of becoming an experimental project, we can move this to be a maintained project.  This will include a move to the github.com/packethost org.

We can move the organization once we have a ready-to-merge PR fulfilling any missing requirements:

* [x] The Maintained badge ![](https://img.shields.io/badge/stability-maintained-green.svg)
* [x] The Maintained Statement in the README.md
* [x] LICENSE
* [x] README.md
* [x] OWNERS.md
* [x] Developer Certificate of Origin https://github.com/apps/dco
* [x] At least two maintainers
* [x] CI/CD
* [x] A Manifest File
* [x] Code of Conduct
* [x] How to Contribute
* [x] SUPPORT.md
* [x] RELEASE.md

**Comment by rainleander** [comment]
Done!
